name: Push

on:
  workflow_call:
    inputs:
      document:
        description: 'The path to the root of the document'
        required: true
        type: string

jobs:
  build:
    # ARM64 processors (M1, M2, M3 series) used on macos-14 images are unsupported, they do not support nested virtualization
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Docker on macOS using Colima, Lima-VM, and Homebrew
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Generate PDF
        run: |
          cd $GITHUB_WORKSPACE/${{ inputs.document }}/ && ./generate-pdf -o main
      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: ${{ github.workspace }}/${{ inputs.document }}/main.pdf
          if-no-files-found: error
