name: Push

on:
  workflow_call:
    inputs:
      document:
        description: 'The path to the root of the document'
        required: true
        type: string
      spell_check_language:
        description: 'Spell check language for LanguageTool'
        required: false
        type: string
        default: 'en-US'
      vale_config:
        description: 'A file path for a Vale config'
        required: false
        type: string
        default: '.vale.ini'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Docker on MacOS Runner
        run: |
          brew install docker
          colima start
      - name: Generate PDF
        run: |
          cd $GITHUB_WORKSPACE/${{ inputs.document }}/ && ./generate-pdf -o main
      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: ${{ github.workspace }}/${{ inputs.document }}/main.pdf
          if-no-files-found: error
