name: Push

on:
  workflow_call:
    inputs:
      document:
        description: 'The path to the root of the document'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Generate PDF
        run: |
          cd ${{ github.workspace }}/${{ inputs.document }}/ && ./generate-pdf -o main-${{ inputs.document }}
      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: main-${{ inputs.document }}.pdf
          path: ${{ github.workspace }}/${{ inputs.document }}/main-${{ inputs.document }}.pdf
          if-no-files-found: error
